In [8]:
#pytorch ile xor fonksiyonunu modelleyeceğiz.
import torch.nn as nn
import torch
import torch.nn.functional as F
import numpy as np

data = np.array([[0,0],[0,1],[1,0],[1,1]]) #Girdimiz
label = np.array([[0],[1],[1],[0]]) #Olması gereken çıktımız.

#Networkü oluşturacak olan class ı oluşturcağız.Bu class nn.Module classından inherit olacak.
class Network(nn.Module):
  def __init__(self):
    super(Network,self).__init__()
    #init fonksiyonuna hangi layerları tutacağını içinde kaç tane layer tutacağını söylemem gerekiyor.
    #fullyconnected layer kullanacağız yani bizim ağlarımızın hepsi birbirlerine aynı derecede bağlı
    #Yani ağırlıklar arasında herhangi bir atlama söz konusu değil.
    self.layer_1 = nn.Linear(2,4) #Birinci katmana iki nöron giriş yaptı ve 4 çıktı yaptı.
    self.layer_2 = nn.Linear(4,4) #Birinci katman 4 çıktı vermişti. Birinci katmanın çıktıları ikinci katmanın girdileri olacağı için, ikinci katmanın input değeri 4 olmuştur.
    self.layer_3 = nn.Linear(4,1)

    #Layerları oluşturduğumuza göre artık ileri yayılım yapabiliriz. Bunun için forward isimi bir fonksiyon oluşturacağız.
    #parametre bu fonksiyon layerlardan gelen çıktıyla çalışacak, bu yüzden output_ parametresini de tanımladık.
  def forward(self,output_):
    #output_ u aktivasyon fonksiyonları ile şekillendirmeliyiz.
    #Aktivasyon fonksiyonu olarak sigmoid i kullandık ve layer1 in output unu şekillendirdik.
    output_ = F.sigmoid(self.layer_1(output_)) #relu fonksiyonlarını da aktivasyon fonksiyon olarak kullanıp şekillendirme yapabiliriz.
    output_ = F.sigmoid(self.layer_2(output_))
    output_ = F.sigmoid(self.layer_3(output_))
    return output_
#Network class ının objesini oluşturmalıyız.
network = Network()
#Optimizer kullanmalyız. SGD Stocastic Gradiant Descent
optimizer = torch.optim.SGD(network.parameters(),lr=0.1,momentum=0.99)
#loss function oluşturulmalı. nn nesneninden Mean Squared Error u çağırarak loss_func ı oluşturacağız.
loss_func = nn.MSELoss()
#epoch belirleyelim. Yani kaç kere veri setini dolaşacağını belirleyelim.
epoch = 1000
for epo in range(epoch):
  #4 tane datamız olduğu için her birine id verebilmek için range i olarak belirledik.
  for idx in range(4):
    data_x = torch.tensor([data[idx]])
    label_x = torch.tensor([label[idx]])
    #optimizer zer_grad metodu ile hesaplamayı yapsın
    optimizer.zero_grad()
    #Gerçek çıktımızı alacağız.
    network_output = network(data_x.float())
    loss = loss_func(network_output,label_x.float()) # Gerçek değerimiz ile elde ettiğimiz değer arasındaki farkı buluyoruz.
    #Geriye doğru yayılımı yapıyoruz.
    loss.backward()
    optimizer.step()
print(network(torch.tensor([data[0]]).float()))
print(network(torch.tensor([data[1]]).float()))
print(network(torch.tensor([data[2]]).float()))
print(network(torch.tensor([data[3]]).float()))








/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1351: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


tensor([[0.0023]], grad_fn=<SigmoidBackward>)
tensor([[0.9991]], grad_fn=<SigmoidBackward>)
tensor([[0.9970]], grad_fn=<SigmoidBackward>)
tensor([[0.0010]], grad_fn=<SigmoidBackward>)
